name: Publish nightly version to NPM

on:
  push:
    branches:
      - v1.x-nightly

permissions:
  id-token: write
  contents: write

jobs:
    publish:
        runs-on: [ubuntu-latest]
        environment:
          name: luminix-publisher-environment
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 24
            registry-url: https://registry.npmjs.org/

        - uses: paulhatch/semantic-version@v5.4.0
          id: semver
          with:
            tag_prefix: v
            version_format: "${major}.${minor}.${patch}-nightly${increment}"
            enable_prerelease_mode: true

        - name: Build, Tag & Publish
          run: |
            npm install
            npm test
            npm run build
            npm version ${{ steps.semver.outputs.version }} --no-git-tag-version
            echo "Publishing version ${{ steps.semver.outputs.version }}..."
            npm publish --tag nightly

        - name: Publish Github Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ steps.semver.outputs.version_tag }}
            target_commitish: ${{ github.sha }}
            draft: false
            prerelease: true